# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patcher4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import urllib.request
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(785, 475)
        MainWindow.setMinimumSize(QtCore.QSize(785, 475))
        MainWindow.setMaximumSize(QtCore.QSize(785, 475))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: transparent;\n"
"}")
        MainWindow.setWindowIcon(QtGui.QIcon('./patcher.ico'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.bgImg = QtWidgets.QLabel(self.centralwidget)
        self.bgImg.setGeometry(QtCore.QRect(3, -3, 791, 476))
        self.bgImg.setText("")
        self.bgImg.setPixmap(QtGui.QPixmap("./img/patcherBg.png"))
        self.bgImg.setScaledContents(True)
        self.bgImg.setObjectName("bgImg")
        self.languageBt = QtWidgets.QPushButton(self.centralwidget)
        self.languageBt.setEnabled(True)
        self.languageBt.setGeometry(QtCore.QRect(635, 52, 30, 30))
        self.languageBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.languageBt.setStyleSheet("background-color: transparent;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/languageBt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.languageBt.setIcon(icon)
        self.languageBt.setIconSize(QtCore.QSize(30, 30))
        self.languageBt.setObjectName("languageBt")
        self.optionsBt = QtWidgets.QPushButton(self.centralwidget)
        self.optionsBt.setEnabled(True)
        self.optionsBt.setGeometry(QtCore.QRect(714, 129, 30, 30))
        self.optionsBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.optionsBt.setStyleSheet("background-color: transparent;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./img/settingsBt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optionsBt.setIcon(icon1)
        self.optionsBt.setIconSize(QtCore.QSize(25, 25))
        self.optionsBt.setObjectName("optionsBt")
        self.gameStartBt = QtWidgets.QPushButton(self.centralwidget)
        self.gameStartBt.setEnabled(True)
        self.gameStartBt.setGeometry(QtCore.QRect(668, 350, 99, 98))
        self.gameStartBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gameStartBt.setStyleSheet("QPushButton{\n"
"border-radius: 65px;\n"
"background-image: url(\'./img/play.png\');\n"
"}\n"
"QPushButton:hover {\n"
"background-image: url(\'./img/playHover.png\');\n"
"}\n"
"QPushButton::pressed {\n"
"background-image: url(\'./img/playHit.png\');\n"
"}\n"
"QPushButton:disabled {\n"
"background-image: url(\'./img/playDisabled.png\');\n"
"}")
        self.gameStartBt.setObjectName("gameStartBt")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(273, 404, 345, 10))
        self.progressBar.setMinimumSize(QtCore.QSize(345, 1))
        self.progressBar.setMaximumSize(QtCore.QSize(345, 12))
        self.progressBar.setStyleSheet("QProgressBar {\n"
         "    border: 1px solid rgb(117, 86, 42);\n"
         "    border-radius: 5px;\n"
         "    background: rgba(117, 86, 42, 180);\n"
         "}\n"
         "\n"
         "QProgressBar::chunk {\n"
         "    background-color: qlineargradient(spread:pad, x1:0.550955, y1:0.182, x2:0.55, y2:0.068, stop:0 rgba(248, 224, 120, 255), stop:1 rgba(255, 255, 255, 255));\n"
         "    border-radius: 4px;\n"
         "}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(383, 124, 331, 201))
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border-radius: 20px;\n"
"border-bottom-left-radius: 80px;\n"
"border-top-right-radius: 80px")
        self.widget.setObjectName("widget")
        self.patchNotes = QtWidgets.QTextBrowser(self.widget)
        self.patchNotes.setGeometry(QtCore.QRect(10, 11, 311, 181))
        font = QtGui.QFont()
        font.setFamily("NtreevSoft")
        font.setPointSize(14)
        self.patchNotes.setFont(font)
        self.patchNotes.setStyleSheet("background-image: url(\'./img/notesBg.png\');\n"
"border: 2px solid white;")
        self.patchNotes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.patchNotes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.patchNotes.setObjectName("patchNotes")
        self.patchNotesLabel = QtWidgets.QLabel(self.widget)
        self.patchNotesLabel.setGeometry(QtCore.QRect(90, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Exotc350 DmBd BT")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.patchNotesLabel.setFont(font)
        self.patchNotesLabel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.54, y1:1, x2:0.534, y2:0, stop:0 rgba(146, 204, 125, 255), stop:1 rgba(209, 255, 178, 255));\n"
"border-radius: 13px;\n"
"border: 2px solid white;\n"
"color: white;")
        self.patchNotesLabel.setObjectName("patchNotesLabel")
        self.auxProgressImg = QtWidgets.QLabel(self.centralwidget)
        self.auxProgressImg.setGeometry(QtCore.QRect(240, 340, 65, 71))
        self.auxProgressImg.setText("")
        self.auxProgressImg.setObjectName("auxProgressImg")
        movie = QtGui.QMovie('./img/updateProgress.gif')
        self.auxProgressImg.setMovie(movie)
        movie.start()
        self.logoImg = QtWidgets.QLabel(self.centralwidget)
        self.logoImg.setGeometry(QtCore.QRect(313, 44, 251, 71))
        self.logoImg.setScaledContents(True)
        self.logoImg.setText("")
        self.logoImg.setPixmap(QtGui.QPixmap("./img/logo.png"))
        self.logoImg.setObjectName("logoImg")
        self.closeBt = QtWidgets.QPushButton(self.centralwidget)
        self.closeBt.setGeometry(QtCore.QRect(732, 45, 15, 18))
        self.closeBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeBt.setStyleSheet("background-color: transparent;\n"
"color: white;\n"
"font-weight: bold;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./img/closeBt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBt.setIcon(icon2)
        self.closeBt.setIconSize(QtCore.QSize(12, 12))
        self.closeBt.setObjectName("closeBt")
        self.updateBt = QtWidgets.QPushButton(self.centralwidget)
        self.updateBt.setGeometry(QtCore.QRect(676, 90, 30, 30))
        self.updateBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateBt.setStyleSheet("background-color: transparent;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./img/repairBt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateBt.setIcon(icon3)
        self.updateBt.setIconSize(QtCore.QSize(28, 22))
        self.updateBt.setObjectName("updateBt")
        self.progressBarImg = QtWidgets.QLabel(self.centralwidget)
        self.progressBarImg.setEnabled(True)
        self.progressBarImg.setGeometry(QtCore.QRect(233, 329, 551, 141))
        self.progressBarImg.setText("")
        self.progressBarImg.setPixmap(QtGui.QPixmap("./img/updateOverlay.png"))
        self.progressBarImg.setObjectName("progressBarImg")
        self.bgImg.raise_()
        self.languageBt.raise_()
        self.optionsBt.raise_()
        self.widget.raise_()
        self.logoImg.raise_()
        self.closeBt.raise_()
        self.updateBt.raise_()
        self.progressBarImg.raise_()
        self.progressBar.raise_()
        self.auxProgressImg.raise_()
        self.gameStartBt.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.patchNotesUrl = "http://example.com/downloads/file.format" # YOUR PATCHNOTES URL
        for line in urllib.request.urlopen(self.patchNotesUrl):
                self.patchNotesInfo = line.decode('utf-8')

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Patcher Name"))
        self.patchNotes.setHtml(_translate("MainWindow", self.patchNotesInfo))
        self.patchNotesLabel.setText(_translate("MainWindow", "Patch Notes"))
